cd "j:/Learn/K210_example/K210_AIRV/K210_AIRV/Example/K210_LCD/build"
SET ALLUSERSPROFILE=C:\ProgramData
SET APPDATA=C:\Users\26062\AppData\Roaming
SET CommonProgramFiles=C:\Program Files\Common Files
SET CommonProgramFiles(x86)=C:\Program Files (x86)\Common Files
SET CommonProgramW6432=C:\Program Files\Common Files
SET COMPUTERNAME=DESKTOP-REMQCP2
SET ComSpec=C:\WINDOWS\system32\cmd.exe
SET DriverData=C:\Windows\System32\Drivers\DriverData
SET FPS_BROWSER_APP_PROFILE_STRING=Internet Explorer
SET FPS_BROWSER_USER_PROFILE_STRING=Default
SET HOMEDRIVE=C:
SET HOMEPATH=\Users\26062
SET KENDRYTE_IDE_LOCAL_PACKAGE_DIR=J:\Kendryte_IDE\KendryteIDE\LocalPackage
SET KENDRYTE_IDE_UPDATER=J:\Kendryte_IDE\KendryteIDE\Updater\electron.exe
SET KENDRYTE_IDE_UPDATER_CONTENT_ROOT=J:\Kendryte_IDE\KendryteIDE
SET KENDRYTE_IDE_UPDATER_IS_BUILT=yes
SET KENDRYTE_IDE_UPDATER_PIPE=\\?\pipe\C:\Users\26062\AppData\Local\Temp\KendryteIDE_Cache\55401_updater.sock
SET KENDRYTE_IDE_UPDATER_PIPE_ID=1
SET LOCALAPPDATA=C:\Users\26062\AppData\Local
SET LOGONSERVER=\\DESKTOP-REMQCP2
SET NUMBER_OF_PROCESSORS=4
SET OneDrive=C:\Users\26062\OneDrive
SET OneDriveConsumer=C:\Users\26062\OneDrive
SET OS=Windows_NT
SET Path=j:\Kendryte_IDE\KendryteIDE\bin;J:\Kendryte_IDE\KendryteIDE\LocalPackage\toolchain\bin;J:\Kendryte_IDE\KendryteIDE\LocalPackage\cmake\bin;J:\Kendryte_IDE\KendryteIDE\LocalPackage\jlink;J:\Kendryte_IDE\KendryteIDE\LocalPackage\clang-format\bin;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0;C:\WINDOWS\System32\OpenSSH
SET PATHEXT=.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC;.PY;.PYW
SET PROCESSOR_ARCHITECTURE=AMD64
SET PROCESSOR_IDENTIFIER=Intel64 Family 6 Model 58 Stepping 9, GenuineIntel
SET PROCESSOR_LEVEL=6
SET PROCESSOR_REVISION=3a09
SET ProgramData=C:\ProgramData
SET ProgramFiles=C:\Program Files
SET ProgramFiles(x86)=C:\Program Files (x86)
SET ProgramW6432=C:\Program Files
SET PSModulePath=C:\Program Files\WindowsPowerShell\Modules;C:\WINDOWS\system32\WindowsPowerShell\v1.0\Modules
SET PUBLIC=C:\Users\Public
SET PyCharm=C:\Program Files\JetBrains\PyCharm 2019.3.4\bin;
SET SESSIONNAME=Console
SET SystemDrive=C:
SET SystemRoot=C:\WINDOWS
SET SYSTEM_TEMP=C:\Users\26062\AppData\Local\Temp
SET TEMP=C:\Users\26062\AppData\Local\Temp\KendryteIDE_Cache
SET TMP=C:\Users\26062\AppData\Local\Temp\KendryteIDE_Cache
SET TMPDIR=C:\Users\26062\AppData\Local\Temp\KendryteIDE_Cache
SET USERDOMAIN=DESKTOP-REMQCP2
SET USERDOMAIN_ROAMINGPROFILE=DESKTOP-REMQCP2
SET USERNAME=26062
SET USERPROFILE=C:\Users\26062
SET VSCODE_CWD=C:\WINDOWS\system32
SET VSCODE_IPC_HOOK=\\.\pipe\112c5dce558c3c15695513d615454c73-1.34.1-beta-main-sock
SET VSCODE_LOGS=J:\Kendryte_IDE\KendryteIDE\UserData\latest\user-data\logs\20200404T141633
SET VSCODE_NLS_CONFIG={"locale":"zh-cn","availableLanguages":{"*":"zh-cn"},"_languagePackId":"2ae16f5a9a23c98b985a67d503c3ac22.zh-cn","_translationsConfigFile":"J:\\Kendryte_IDE\\KendryteIDE\\UserData\\latest\\user-data\\clp\\2ae16f5a9a23c98b985a67d503c3ac22.zh-cn\\tcf.json","_cacheRoot":"J:\\Kendryte_IDE\\KendryteIDE\\UserData\\latest\\user-data\\clp\\2ae16f5a9a23c98b985a67d503c3ac22.zh-cn","_resolvedLanguagePackCoreLocation":"J:\\Kendryte_IDE\\KendryteIDE\\UserData\\latest\\user-data\\clp\\2ae16f5a9a23c98b985a67d503c3ac22.zh-cn\\e4de46724de34a5f46541818e9fee25971ac9969","_corruptedFile":"J:\\Kendryte_IDE\\KendryteIDE\\UserData\\latest\\user-data\\clp\\2ae16f5a9a23c98b985a67d503c3ac22.zh-cn\\corrupted.info","_languagePackSupport":true}
SET VSCODE_NODE_CACHED_DATA_DIR=J:\Kendryte_IDE\KendryteIDE\UserData\latest\user-data\CachedData\e4de46724de34a5f46541818e9fee25971ac9969
SET VSCODE_PATH=J:\Kendryte_IDE\KendryteIDE\Application\app_1.34.1-beta_20190802.2
SET VSCODE_PID=14852
SET VSCODE_PORTABLE=J:\Kendryte_IDE\KendryteIDE\UserData\latest
SET windir=C:\WINDOWS
SET XILINX_FOR_ALTIUM_OVERRIDE= 
SET PYTHONHOME=J:/Kendryte_IDE/KendryteIDE/LocalPackage/python2library
SET PYTHONPATH=J:/Kendryte_IDE/KendryteIDE/LocalPackage/python2library;J:/Kendryte_IDE/KendryteIDE/LocalPackage/toolchain/share/gdb/python
SET PYTHONDONTWRITEBYTECODE=yes
SET CMAKE_MAKE_PROGRAM=make
SET KENDRYTE_IDE=yes
SET LANG=en_US.utf-8
"J:/Kendryte_IDE/KendryteIDE/LocalPackage/cmake/bin/cmake.exe" --build j:/Learn/K210_example/K210_AIRV/K210_AIRV/Example/K210_LCD/build -- -j 3